Assume VCS info is UTF-8 encoded
Fixes an error caused by non-ASCII committer names such as "Michael Pürrer":

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 61: ordinal not in range(128)