FITSFileIO: try a different cast to avoid errors on Macs
- Specifically,
  error: cast from 'CHAR *' (aka 'char *') to 'CHAR **' (aka 'char **')
  increases required alignment from 1 to 8